### ISSUE TITLE
TypeError: Class constructor DiffEngine cannot be invoked without 'new'

### ISSUE THREAD

**Issue by mohnen** [Spence-S/human-object-diff#6]
With the example from usage
`const humanDiff = require('human-object-diff');
const lhs = { foo: 'bar' };
const rhs = { foo: 'baz' };
const options = {};
const diff = humanDiff(lhs, rhs, options);`

I get this error
`Thrown:
TypeError: Class constructor DiffEngine cannot be invoked without 'new'`

node version 11.10.0

**Comment by Spence-S** [comment]
sorry @mohnen the documentation is currently not up to date. I haven't devoted more time to this project as I found an easier solution to the reason i was developing it in the first place. - I plan on catching up on this in the next few weeks. Thanks for letting me know. If you want to use you can do something like:
```js
const Diff = require('human-object-diff');
const difference = new Diff({})
difference.diff(lhs,rhs)
```
I will leave this open until I can get back to it. 

PRs would be accepted as well!!!

**Comment by saschanaz** [comment]
> as I found an easier solution to the reason i was developing it in the first place.

Could you share what easier solution you found is? Thanks!

**Comment by Spence-S** [comment]
@saschanaz I was originally creating this to support user friendly diffs for certain fields in mongoose when the documents were updated. However, this became its own thing in the process. Also if you want a good object diff library that you can expand on this lib is using https://github.com/flitbit/diff under the hood for primary diffiing. 

creating this plugin was a better solution for me. 
https://github.com/Spence-S/mongoose-monitor-fields-plugin

**Comment by Spence-S** [comment]
Updated docs for the current API
